# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  name: AgentPool
  demands:
  - agent.name -equals VM0  

variables:
  azureServiceConnection: 'azuresub'
  resourceGroupName: 'Bicep'
  location: 'eastus'
  templateFile: 'main.bicep'

steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azuresub'
        scriptType: 'batch'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az --version
          az group create --name $(resourceGroupName) --location $(location)
          az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile)